---
title: "Myanmar Census Analysis"
output: html_document
---
## Outline


Using the Myanmar 2014 census data  for investigating the implications of the ageing of the population structure on farming households. 

#### Household level
At the household level we are particularly interested in investigating the household structure of the farming population and how that relates to intra-household labour availability. This would involve a descriptive analysis of households with members in farming occupations, including the associations with the following variables:

- former household members that have migrated internationally;
- household members with disabilities;
- proxies for household income level (based on housing characteristics and if possible derived socioeconomic class from occupation?)

#### Township level 
The role of internal migration on household labour availability can only be investigated at the township level. The question is therefore to what extent does intra-household labour availability vary across areas (townships), urban/rural relative to levels and causes of out-migration. 

#### Individual level
At the individual level we  are interested in people's migration status (and reason) and it's determinants, in particular how they vary by demographic characteristics and geographically. 


