---
title: "Myanmar Census Analysis Briefing"
author: "mz"
date: "22.11.2016"
output:
  html_document: default
  word_document html_document: default
toc: yes
---
Variable Code | name | notes  |
--------------|------|--------|
Q1-Ind-ID-X   | ID  |   relevant for matching only |
Q2-Ind-Name-X | Name| not relevant/accessible |
Q3-Ind-HHRel-c11| Relationship to head of HH |     |
Q4-Ind-Sex-c2 | Sex |   |
Q5-Ind-Age-c98 | Age  | up to "98 or older"  |
Q6-Ind-MS-c5 | Marital status |    |
Q7-Ind-Religion-c7 | Religion |   |
Q8-Ind-Ethnicity-c135 | Ethnicity  | post coded? apparently 135 groups recognized|
Q9i-Ind-DisSee-c4 | Disability Seeing |   |
Q9ii-Ind-DisHear-c4 | Disability Hearing |   |
Q9iii-Ind-DisWalk-c4 | Disability Walking |   |
Q9iv-Ind-DisCogn-c4 | Disability Remembering or concentrating |   |
Q10-Ind-IDCard-c10 | Type of Identity Card |  |
Q11-Ind-PoBTown-X  | Township code of place of birth - 000 for "here" |  |
Q12-Ind-PoBRuUr-c2 | Place of birth rural or urban |   |
Q13-Ind-ResTown-X  | Township code of usual residence - 000 for "here" | |
Q14-Ind-ResRuUr-c2 | Usual residence rural or urban |  |
Q15-Ind-ResDur-c98 | Years in place of usual residence |  |
Q16-Ind-ResMove-c7 | Reason for move here  |   |
Q17-Ind-PrResTown-X  | Township of previous place of residence ||
Q18-IndPrResRuUr-c2 | Previous place of residence rural or urban ||
Q19-Ind-Lit-c2  | Can read and write | (age 5 and above) |
Q20-Ind-EdAtt-c3  | Ever/currently attended school |  (age 5 and above)|
Q21-Ind-EdHing-c19 | Highest level of education attained | (age 5 and above) grouping? |
Q22-Ind-ActStat-c12 | Activity Status | (age 10 and above)  |
Q23-Ind-Occ  | Occupation (ILO)| age 10 and above AND Q22 == employed or self-employed |
Q24-Ind-Ind | Industry (ILO) | age 10 and above AND Q22 == employed or self-employed |
Q25-Ind-ChildB | Number of children born alive | (ever married women over 15) |



# George's Questions

## Part I

